# Generated by Django 6.1.1 on 2026-09-28 17:29

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import banking.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Account numbers have exactly 10 digits."
                            )
                        ],
                    ),
                ),
                ("balance", banking.fields.MoneyField(default=Decimal("0.00"))),
                (
                    "currency",
                    models.CharField(default="EUR", editable=False, max_length=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", banking.fields.MoneyField()),
                ("fee", banking.fields.MoneyField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recipient_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="banking.account",
                    ),
                ),
                (
                    "sender_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="banking.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")], max_length=6
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("welcome_bonus", "Welcome Bonus"),
                            ("transfer", "Transfer"),
                            ("transfer_fee", "Transfer Fee"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "amount",
                    banking.fields.MoneyField(
                        help_text="Always positive; the type says which way it moved."
                    ),
                ),
                (
                    "balance_after",
                    banking.fields.MoneyField(help_text="Account balance right after this entry."),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="banking.account",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="banking.transfer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="account_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="transfer_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee__gte", 0)), name="transfer_fee_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sender_account", models.F("recipient_account")), _negated=True
                ),
                name="transfer_between_distinct_accounts",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["account", "-created_at"], name="transaction_history_idx"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["credit", "debit"])),
                name="transaction_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["welcome_bonus", "transfer", "transfer_fee"])),
                name="transaction_kind_valid",
            ),
        ),
    ]
