# Generated by Django 6.1.1 on 2026-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Client-chosen key that makes retrying this transfer safe; empty if none.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("sender_account", "idempotency_key"),
                name="transfer_idempotency_key_unique_per_sender",
            ),
        ),
    ]
